name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: Run Unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo 'DyNaMiXx7'
    - name: Start application
      run: npm start &
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Run Integration tests
      run: npm run test:ui